# Generated by Django 3.0.8 on 2020-08-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0002_auto_20200801_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='nlong',
            field=models.URLField(max_length=400, unique=True),
        ),
        migrations.AlterField(
            model_name='urls',
            name='short',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
